### ISSUE TITLE
I found some error when  "npm run make"

### ISSUE THREAD

**Issue by zupaazhai** [reactjs/react-php-v8js#24]
> 0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\Program Files\nodejs\\node.exe',
> 1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
> 1 verbose cli   'run',
> 1 verbose cli   'make' ]
> 2 info using npm@2.11.2
> 3 info using node@v0.12.5
> 4 verbose run-script [ 'premake', 'make', 'postmake' ]
> 5 info premake react-php-v8js@1.0.0
> 6 info make react-php-v8js@1.0.0
> 7 verbose unsafe-perm in lifecycle true
> 8 info react-php-v8js@1.0.0 Failed to exec make script
> 9 verbose stack Error: react-php-v8js@1.0.0 make: `npm run make-dev && npm run make-min && npm run make-table`
> 9 verbose stack Exit status 1
> 9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
> 9 verbose stack     at EventEmitter.emit (events.js:110:17)
> 9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
> 9 verbose stack     at ChildProcess.emit (events.js:110:17)
> 9 verbose stack     at maybeClose (child_process.js:1015:16)
> 9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
> 10 verbose pkgid react-php-v8js@1.0.0
> 11 verbose cwd C:\Users\supachai.w\Desktop\react\react-php-v8js\example
> 12 error Windows_NT 6.3.9600
> 13 error argv "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "make"
> 14 error node v0.12.5
> 15 error npm  v2.11.2
> 16 error code ELIFECYCLE
> 17 error react-php-v8js@1.0.0 make: `npm run make-dev && npm run make-min && npm run make-table`
> 17 error Exit status 1
> 18 error Failed at the react-php-v8js@1.0.0 make script 'npm run make-dev && npm run make-min && npm run make-table'.
> 18 error This is most likely a problem with the react-php-v8js package,
> 18 error not with npm itself.
> 18 error Tell the author that this fails on your system:
> 18 error     npm run make-dev && npm run make-min && npm run make-table
> 18 error You can get their info via:
> 18 error     npm owner ls react-php-v8js
> 18 error There is likely additional logging output above.
> 19 verbose exit [ 1, true ]

How do I solve this issue, Thank.

**Comment by zpao** [comment]
Looks like you're running on Windows and I can't remember if that supports the `&&` in commands so you might just need to run each step individually. Though also each of those is using Unixy things so they might not work either. You can try to convert these commands to something that will work on Windows: https://github.com/reactjs/react-php-v8js/blob/master/example/package.json#L6-L9

FWIW, this project is not actively maintained so you'll be on your own to work that out, sorry.

**Comment by giancarlo88** [comment]
I had a similar error, and mine was caused by a small syntax error in my JSX file.
